// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate/CLI operations need a direct (non-pooled) connection so DDL and
  // the shadow database work reliably; the app itself connects separately
  // via DATABASE_URL (pooled) through the driver adapter in src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
